version: "3.9"
services:
  db:
    image: mariadb:latest
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    - ./var/lib/mysql:/var/lib/mysql
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 1024M
    env_file:
    - ./env_vars/.env_db_mysql
    secrets:
    - MYSQL_USER
    - MYSQL_PASSWORD
    - MYSQL_ROOT_PASSWORD
    networks:
    - network
  php:
    depends_on:
    - db
    image: dramos777/php-to-glpi:1.0
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    - ./glpi-project:/var/www/html/glpi/:ro
    - ./glpi-project/config/:/var/www/html/glpi/config/
    - ./glpi-project/files/:/var/www/html/glpi/files/
    - ./glpi-project/lib/:/var/www/html/glpi/lib/
    - ./glpi-project/lib/:/var/www/html/glpi/plugins/
    networks:
    - network
  web:
    depends_on:
    - db
    - php
    image: nginx:alpine 
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./nginx/conf/nginxconfig.io/:/etc/nginx/nginxconfig.io/:ro
    - ./nginx/conf/sites-available/:/etc/nginx/sites-available/:ro
    - ./nginx/conf/sites-enabled/:/etc/nginx/sites-enabled/:ro
    - ./certificates/fullchain.pem:/etc/nginx/ssl/live/seudominio.abc/fullchain.pem:ro
    - ./certificates/privkey.pem:/etc/nginx/ssl/live/seudominio.abc/privkey.pem:ro
    - ./certificates/dhparam.pem:/etc/nginx/dhparam.pem:ro
    - ./glpi-project:/var/www/html/glpi/:ro
    - ./glpi-project/config/:/var/www/html/glpi/config/
    - ./glpi-project/files/:/var/www/html/glpi/files/
    - ./glpi-project/lib/:/var/www/html/glpi/lib/
    - ./glpi-project/lib/:/var/www/html/glpi/plugins/
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
    ports:
    - "80:80"
    - "443:443" 
    networks:
    - network
networks:
  network:
secrets:
  MYSQL_USER:
    file: ./env_vars/.MYSQL_USER
  MYSQL_PASSWORD:
    file: ./env_vars/.MYSQL_PASSWORD
  MYSQL_ROOT_USER:
    file: ./env_vars/.MYSQL_ROOT_USER
  MYSQL_ROOT_PASSWORD:
    file: ./env_vars/.MYSQL_ROOT_PASSWORD
