version: "3.9"
services:
  db:
    image: mariadb:latest
    volumes:
    - db:/var/lib/mysql
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 1024M
    environment:
      MYSQL_ROOT_PASSWORD: glpi
      MYSQL_ROOT_HOST: localhost
      MYSQL_DATABASE: glpi
      MYSQL_USER: glpi
      MYSQL_PASSWORD: glpi
    networks:
    - network
  php:
    depends_on:
    - db
    image: dramos777/php-to-glpi:1.0
    volumes:
    - ./glpi-project:/var/www/html/glpi/:ro
    - ./glpi-project/config/:/var/www/html/glpi/config/
    - ./glpi-project/files/:/var/www/html/glpi/files/
    - ./glpi-project/lib/:/var/www/html/glpi/lib/
    - ./glpi-project/lib/:/var/www/html/glpi/plugins/
    networks:
    - network
  web:
    depends_on:
    - db
    - php
    image: nginx:alpine 
    volumes:
    - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./nginx/conf/nginxconfig.io/:/etc/nginx/nginxconfig.io/:ro
    - ./nginx/conf/sites-available/:/etc/nginx/sites-available/:ro
    - ./nginx/conf/sites-enabled/:/etc/nginx/sites-enabled/:ro
    - ./certificates/fullchain.pem:/etc/nginx/ssl/live/seudominio.abc/fullchain.pem:ro
    - ./certificates/privkey.pem:/etc/nginx/ssl/live/seudominio.abc/privkey.pem:ro
    - ./certificates/dhparam.pem:/etc/nginx/dhparam.pem:ro
    - ./glpi-project:/var/www/html/glpi/:ro
    - ./glpi-project/config/:/var/www/html/glpi/config/
    - ./glpi-project/files/:/var/www/html/glpi/files/
    - ./glpi-project/lib/:/var/www/html/glpi/lib/
    - ./glpi-project/lib/:/var/www/html/glpi/plugins/
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
    ports:
    - "80:80"
    - "443:443" 
    networks:
    - network
networks:
  network:
volumes:
  db:
